# Generated by Django 4.0.2 on 2022-10-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='candidate',
            new_name='Candidate',
        ),
    ]
